apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-todolist-sndt
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: api-todolist.laranjeira.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-todolist-sndt
                port:
                  number: 3000
