apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-todolist-sndt
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-todolist.seu-dominio.com
    secretName: api-todolist-tls
  rules:
  - host: api-todolist.laranjeira.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-todolist-sndt
            port:
              number: 3000
