name: CI - Build & Push

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE: laranjeirajuliano/api-todolist-sndt

jobs:
  CI:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Docker Hub Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
            ${{ env.DOCKER_IMAGE }}:latest
